title: p-matter # name of the site
author: p-matter # name of site's author
email: mail@p-matter.work # email of site's author
url: # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
  p-matter is shorten version of _*Programmable Matter*_

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "<- Back" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
